//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMeasure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SyncMeasure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./all.png.
        /// </summary>
        internal static string ALL_GRAPH {
            get {
                return ResourceManager.GetString("ALL_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./cvvArms.png.
        /// </summary>
        internal static string ARM_CVV_GRAPH {
            get {
                return ResourceManager.GetString("ARM_CVV_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmPosX.
        /// </summary>
        internal static string ARM_POS_X {
            get {
                return ResourceManager.GetString("ARM_POS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmPosY.
        /// </summary>
        internal static string ARM_POS_Y {
            get {
                return ResourceManager.GetString("ARM_POS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmPosZ.
        /// </summary>
        internal static string ARM_POS_Z {
            get {
                return ResourceManager.GetString("ARM_POS_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bulk.
        /// </summary>
        internal static string BULK {
            get {
                return ResourceManager.GetString("BULK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi
        ///\b SyncMeasure Controls \b0
        ///\line\line
        ///- To analyze a file, it needs to be loaded and then measured.
        ///- Loading cvs can be done by dragging csv file to SyncMeasure or by clicking the Load button or by ctrl+L.
        ///\line\line
        ///- Sync Measurement can be done by clicking Enter or by clicking Measure button.s
        ///\line\line
        ///- After parsing data, you can double click the graphs to expand. Use mouse wheel to zoom in / out.
        ///\line\line
        ///- Combine option is intended to combine &apos;Alone&apos; files which holds dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbow.
        /// </summary>
        internal static string ELBOW {
            get {
                return ResourceManager.GetString("ELBOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./cvvElbows.png.
        /// </summary>
        internal static string ELBOW_CVV_GRAPH {
            get {
                return ResourceManager.GetString("ELBOW_CVV_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElbowPosX.
        /// </summary>
        internal static string ELBOW_POS_X {
            get {
                return ResourceManager.GetString("ELBOW_POS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElbowPosY.
        /// </summary>
        internal static string ELBOW_POS_Y {
            get {
                return ResourceManager.GetString("ELBOW_POS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElbowPosZ.
        /// </summary>
        internal static string ELBOW_POS_Z {
            get {
                return ResourceManager.GetString("ELBOW_POS_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameID.
        /// </summary>
        internal static string FRAME_ID {
            get {
                return ResourceManager.GetString("FRAME_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture.
        /// </summary>
        internal static string GESTURE {
            get {
                return ResourceManager.GetString("GESTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab.
        /// </summary>
        internal static string GRAB {
            get {
                return ResourceManager.GetString("GRAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrabAngle.
        /// </summary>
        internal static string GRAB_ANGLE {
            get {
                return ResourceManager.GetString("GRAB_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./grabStrength.png.
        /// </summary>
        internal static string GRAB_GRAPH {
            get {
                return ResourceManager.GetString("GRAB_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrabStrength.
        /// </summary>
        internal static string GRAB_STRENGTH {
            get {
                return ResourceManager.GetString("GRAB_STRENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        internal static string HAND {
            get {
                return ResourceManager.GetString("HAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./cvvHands.png.
        /// </summary>
        internal static string HAND_CVV_GRAPH {
            get {
                return ResourceManager.GetString("HAND_CVV_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand_ID.
        /// </summary>
        internal static string HAND_ID {
            get {
                return ResourceManager.GetString("HAND_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandPosX.
        /// </summary>
        internal static string HAND_POS_X {
            get {
                return ResourceManager.GetString("HAND_POS_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandPosY.
        /// </summary>
        internal static string HAND_POS_Y {
            get {
                return ResourceManager.GetString("HAND_POS_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandPosZ.
        /// </summary>
        internal static string HAND_POS_Z {
            get {
                return ResourceManager.GetString("HAND_POS_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandType.
        /// </summary>
        internal static string HAND_TYPE {
            get {
                return ResourceManager.GetString("HAND_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandVelX.
        /// </summary>
        internal static string HAND_VEL_X {
            get {
                return ResourceManager.GetString("HAND_VEL_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandVelY.
        /// </summary>
        internal static string HAND_VEL_Y {
            get {
                return ResourceManager.GetString("HAND_VEL_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandVelZ.
        /// </summary>
        internal static string HAND_VEL_Z {
            get {
                return ResourceManager.GetString("HAND_VEL_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HandsInFrame.
        /// </summary>
        internal static string HANDS_IN_FRAME {
            get {
                return ResourceManager.GetString("HANDS_IN_FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinch.
        /// </summary>
        internal static string PINCH {
            get {
                return ResourceManager.GetString("PINCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./pinchStrength.png.
        /// </summary>
        internal static string PINCH_GRAPH {
            get {
                return ResourceManager.GetString("PINCH_GRAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinchStrength.
        /// </summary>
        internal static string PINCH_STRENGTH {
            get {
                return ResourceManager.GetString("PINCH_STRENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string PITCH {
            get {
                return ResourceManager.GetString("PITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string ROLL {
            get {
                return ResourceManager.GetString("ROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .SyncMeasureSettings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string TIMESTAMP {
            get {
                return ResourceManager.GetString("TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMeasure.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaw.
        /// </summary>
        internal static string YAW {
            get {
                return ResourceManager.GetString("YAW", resourceCulture);
            }
        }
    }
}
